server:
  port: 8025
keycloak:
  auth-server-url: http://localhost:9090
  realm: recipegenius
  client: recipegenius
  credentials:
    secret: d9FB9gC5ea13UzM38HdcGaniSe7oVdhR
  admin:
    username: xdd
    password: xdd

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/recipegenius"





